### ISSUE TITLE
Problems with the read/write rights

### ISSUE THREAD

**Issue by anton-liubushkin** [undavide/PS-Installer#1]
When trying to install I get the following error:

```
Installation failed:    Message: Unable to create folder '~/Library/Application%20Support/Adobe/CEP/extensions/com.nvkznemo.uberstock.extension' (I/O-Fehler)
Please create it manually and run this script again.
        File: ~/Downloads/UberStock-Photoshop-plugin/install.jsx
        Line: 124
        Error Name: Error
        Error Number: 9002      [install.jsx]
anonymous([Error:Fehler: Unable to create folder '~/Library/Application%20Support/Adobe/CEP/extensions/com.nvkznemo.uberstock.extension' (I/O-Fehler)\nPlease create it manually and run this script again.])
```

I created the mentioned folder manually but the error shows again. I also checked the read/write rights of the folder. system and admin have read/write rights.

Whats wrong? Do you have an suggestion?

**Comment by undavide** [comment]
Hi Anton,
are you on Mac or PC? If the latter is the case, have you tried running PS As Admin? (it is required even if the user is logged as Admin. Please let me know!
Thanks -Davide

**Comment by anton-liubushkin** [comment]
This error sent me one of the buyers. He has a Mac.
We got around it by copying all the files from "ASSETS/HTML" in to "~/Library/Application%20Support/Adobe/CEP/extensions/com.nvkznemo.uberstock.extension".

I will try to learn from him the details.

**Comment by anton-liubushkin** [comment]
no, he started ps in default mode. What he tried: he checked the folder rights and added the admin (only system & group where defined) to r/w. But that didn't worked. He didn't try the admin start.

**Comment by cameronmcefee** [comment]
I ran into this one with a customer today too. Since I can't reproduce it, it's tough for me to test. @undavide, do you know how that install path is generated? The `%20`s in the file path will fail if you use them in the Terminal. Could it be that those are breaking things?

For example:

```
Camerons-MacBook-Pro:guideguide cameronmcefee$ open ~/Library/Application%20Support/
The file /Users/cameronmcefee/Library/Application%20Support does not exist.

Camerons-MacBook-Pro:guideguide cameronmcefee$ open ~/Library/Application\ Support/
Camerons-MacBook-Pro:guideguide cameronmcefee$ 
```

I don't expect that to be the problem because if that were the case, it would probably break universally, but with Adobe, you never really know.

**Comment by undavide** [comment]
Merging in [this issue](https://github.com/undavide/PS-Installer/issues/7).
