### ISSUE TITLE
Not working with Photoshop CC 2014

### ISSUE THREAD

**Issue by thameera** [undavide/PS-Installer#2]
I tried the installing the given example for Photoshop CC 2014 (both system-wide and user installs). The script copies to the locations without any errors. But the extension doesn't show up after restarting Photoshop.

What could have gone wrong?

EDIT: Even manually copying the files to the locations doesn't seem to work.

**Comment by undavide** [comment]
Hi @thameera,
if you have a look ad the content of the ASSETS/HTML folder, you'll see it contains just a couple of placeholder files (an empty example.html and an empty CSXS/manifest.xml file) so no surprise you don't see any extension in PS.
If the files are deployed correctly, let's say it works :-) I understand it can be misleading though, I'll add a proper Hello World extension in next update. 
Thanks for pointing out!
-Davide

**Comment by thameera** [comment]
Ah, forgot to check the manifest.xml file, thanks! Added a proper manifest and an index.html file; and it worked in my machine.
So basically, just copying the signed (and extracted) extension folder to "C:\Program Files (x86)\Common Files\Adobe\CEP\extensions" should work, right?

The thing is I had installed an extension from their online store, and it was installed in this folder. When I copied my extension to same location it worked.
Then I removed both of them and manually created the folder and copied. Now Photoshop doesn't recognize the extension. (I'm testing this coz this extension has to be deployed to other users)

Still very confused about the whole thing. :S

**Comment by undavide** [comment]
Hi @thameera, 
it might be because of signing/timestamping? If you have a deployed and working extension and you change, remove, edit, touch a file (even think about it intensely I'd say :-) it won't work anymore since you've broken the signing.

**Comment by thameera** [comment]
Hi @undavide,
Finally found the issue. In my manifest.xml I had added PHXS under HostList, but not PHSP. The docs only mention PHXS in most places, but has mentioned PHSP in one place.
Apparently PHSP - Photoshop, PHXS - Photoshop Extended.

The problem's fixed now, though I have no idea what Photoshop Extended is. :D (Remember there was a CS6 Extended, but thought that was just a single version).

Thanks!
