### ISSUE TITLE
Init.json is wrong?

### ISSUE THREAD

**Issue by TravisEvashkevich** [undavide/PS-Installer#4]
Hey, I tried filling in my own info and such into the Init.JSON and PS complains about the very first line. Thought I messed up somewhere but even trying to drop the installer.jsx into PS right from a fresh download from here gives this message
http://puu.sh/njrLV/453f12e447.png
I tried sticking ; on all the line ends but that didn't help much either. Json formatters say it is malformed as well. 
This was in CS6, CC 2014 and CC 2015 that they all give an error.

**Comment by undavide** [comment]
@TravisEvashkevich, is this still an issue (the code has been updated)?
Please let me know that I'll close this. Thank you

**Comment by TravisEvashkevich** [comment]
Hey,
Never got it to work before and gave up. Just wrote a batch script to copy folders to where they needed to be.

I can try again if you've changed something but I won't be able to for a few days(don't have access to my laptop atm)

**Comment by undavide** [comment]
I fixed a JSON parsing error – I've tried the provided example and it works. I'm doing some spring cleaning in the issues :-) Let me know, no hurry.
(recent problem is: permission issues on Macs)
Thank you
