### ISSUE TITLE
Error Number: 21	[installer.jsx]

### ISSUE THREAD

**Issue by MichaelVortex** [undavide/PS-Installer#5]
Hi Davide, 
# something goes wrong with your install.jsx with the new Photoshop CC-2015.5 :

 Wed Jun 22 2016 09:28:59 GMT+0200
    Company: CS-EXTENSIONS
    Product: Test product
    Product version: 0.3.0
    App: photoshop
    App Version: 17.0.0
    OS: Windows
    Locale: en_US

---

```
Installer Version: 0.1.2
```

 =======================================
## Preflight 

OK: PS version 17 in the range [0, 99]
## Items to be installed 

Installation failed:    Message: undefined is not an object
    File: ~/Desktop/PS-Installer-master/PS-Installer-master/Example/installer.jsx
    Line: 236
    Error Name: TypeError
    Error Number: 21    [installer.jsx]
anonymous([Error:TypeError: undefined is not an object])

Any ideas? BTW: Thanks alot for your grandiose installer! Big help for me. Best wishes
![cc2015 5_error](https://cloud.githubusercontent.com/assets/20084410/16258982/9f02fea2-3860-11e6-8a52-6e277c42fb35.jpg)

**Comment by undavide** [comment]
Hi Michael,
it's a known issue that I'm going to fix asap – if you want to do it by yourself in the meantime, just add (I'm referring to the JS file, around line 222):

```
dependencyObj = {
      "10": ["SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"],
      "11": ["FLASH_PANEL", "SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"],
      "12": ["FLASH_PANEL", "SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"],
      "13": ["FLASH_PANEL", "SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"],
      "14": ["HTML_PANEL", "SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"],
      "15": ["HTML_PANEL", "SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"],
      "16": ["HTML_PANEL", "SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"],
      "17": ["HTML_PANEL", "SCRIPT", "MAC_PLUGIN", "WIN_PLUGIN", "EXTRA"]
    };
```

This is because CC2015.5 _appears_ to be a point version, yet it's a major version in Photoshop (internal: **17.0**). I've written a blogpost about it, that you can find [here](http://www.davidebarranca.com/2016/06/html-panel-tips-21-photoshop-cc2015-5-2016-survival-guide/).

Thanks for the kind words!

Davide

**Comment by MichaelVortex** [comment]
Thank YOU again Davide!!!

**Comment by undavide** [comment]
Pushed a new version, can you please try that and report back?
Thank you!

**Comment by MichaelVortex** [comment]
Hi Davide,

i've tested it on PC / win10:
CC-2014 and CC-2015: Error Message, but the extension is installed.
CC.2015.5: installation complete.
Hope that will help.

**Comment by MichaelVortex** [comment]
-> i've sent you an email

**Comment by undavide** [comment]
@MichaelVortex what kind of error?

**Comment by MichaelVortex** [comment]
oh, did you not get my email? 
![cc-2014_error_message](https://cloud.githubusercontent.com/assets/20084410/16293653/e4fe1bb0-391b-11e6-8e2c-e9b2a743afab.jpg)

**Comment by undavide** [comment]
I've possibly missed it @MichaelVortex! Are you running PS as an administrator?

**Comment by MichaelVortex** [comment]
Yes, all settings are the same. All PS versions are on the same machine. The folder is installed - but showing the error message.

**Comment by undavide** [comment]
Merging to [this new issue](https://github.com/undavide/PS-Installer/issues/7) – about permissions.
